repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: pipenv run lint-fix
        language: system
        types: [python]
        pass_filenames: false
      - id: format
        name: format
        entry: pipenv run format
        language: system
        types: [python]
        pass_filenames: false
