version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1


jobs:
  plan:
    docker:
      - image: hashicorp/terraform:1.4.2
    working_directory: ~/recommendations/terraform
    steps:
      - checkout:
          path: ~/recommendations
      - run:
          name: terraform fmt
          command: |
            terraform init
            terraform fmt
      - run:
          name: terraform plan
          command: terraform plan -out plan
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: hashicorp/terraform:1.4.2
    working_directory: /home/circleci/my-app
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: terraform apply
          command: terraform apply -auto-approve
  checks:
    docker: 
      - image: cimg/python:3.10
        environment:
          DATABASE_URL: postgresql://test:test@localhost:5432/postgres
      - image: cimg/postgres:15.2
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            pip install pipenv
      - run:
          name: Install dependencies
          command: |
            pipenv install --dev
      - run:
          name: Run lint-check
          command: pipenv run lint-check
      - run: 
          name: Run format-check
          command: pipenv run format-check
      - run:
          name: Migrate test db
          command: pipenv run alembic upgrade head
      - run:
          name: Run tests
          command: pipenv run pytest

workflows:
  terraform:
    jobs:
      - plan:
          context: INFRASTRUCTURE
      - review_plan:
          context: INFRASTRUCTURE
          requires:
            - plan
          type: approval
          filters:
            branches:
              ignore: main
      - apply:
          context: INFRASTRUCTURE
          requires:
            - plan
          filters:
            branches:
              only: main
  build-and-deploy:
    jobs:
      - checks
      - aws-ecr/build-and-push-image:
          context: INFRASTRUCTURE
          requires:
            - checks
          repo: recommendations
          tag: latest
