version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  checks:
    executor: 
      name: python/default
      tag: "3.10.8"
    steps:
      - checkout
      - run:
          name: Start PostgreSQL service
          command: |
            docker run -d \
              -p 5432:5432 \
              -e POSTGRES_USER=test \
              -e POSTGRES_PASSWORD=test \
              -e POSTGRES_DB=test \
              circleci/postgres:13-alpine
          background: true
      - run:
          name: Wait for PostgreSQL to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - python/install-packages:
        environment:
          DATABASE_URL: postgresql://test:test@localhost:5432/postgres
          args: --dev
          pkg-manager: pipenv
      - run:
          name: Run lint-check
          command: pipenv run lint-check
      - run: 
          name: Run format-check
          command: pipenv run format-check
      - run:
          name: Run tests
          command: pipenv run pytest

workflows:
  build:
    jobs:
      - checks
